// <auto-generated />
using AptekaInternetowa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AptekaInternetowa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AptekaInternetowa.Models.ProduktM.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena");

                    b.Property<string>("Dawkowanie");

                    b.Property<string>("DodatkoweInformacje");

                    b.Property<string>("Dzialanie");

                    b.Property<int>("LiczbaDostępnychSztuk");

                    b.Property<string>("Nazwa");

                    b.Property<string>("Producent");

                    b.Property<string>("Przeciwwskazania");

                    b.Property<string>("Sklad");

                    b.Property<string>("Wskazania");

                    b.Property<string>("ZdjecieUrl");

                    b.HasKey("Id");

                    b.ToTable("Produkty");
                });
#pragma warning restore 612, 618
        }
    }
}
